apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app: istio-reader
        app.kubernetes.io/instance: istiod
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: istio-reader
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/version: 1.27.0
        helm.sh/chart: istiod-1.27.0
        release: istiod
    name: istio-reader-clusterrole-istio
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: istio-reader-clusterrole-istio
subjects:
    - kind: ServiceAccount
      name: istio-reader-service-account
      namespace: istio-system
