apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: x-clone

servers: 1
agents: 3

kubeAPI:
  host: "127.0.0.1"
  hostPort: "6445"

image: rancher/k3s:v1.32.0-k3s1

network: x-clone

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

# By default, K3D creates its own container registry (inside one of those containers spun up by
# K3D).
#
# The problem is, when we delete the K3D cluster, that container registry (along with the pulled
# container images) go away. So, next time when we re-spinup the cluster, those container images
# need to be repulled.
#
# We're using ligfx/k3d-registry-dockerd to proxy all container pull requests to dockerd. This way,
# container images pulled by K3D, get persisted in the user's host machine. They stay, even when
# we delete the K3D cluster. And get reused when we re-spinup the K3D cluster.
registries:
  create:
    name: x-clone
    image: ligfx/k3d-registry-dockerd:v0.8
    proxy:
      remoteURL: "*"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  config: |
    mirrors:
      "*":
        endpoint:
          - http://x-clone:5000
