apiVersion: v1
data:
    AMBIENT_DNS_CAPTURE: "true"
    AMBIENT_ENABLED: "true"
    AMBIENT_ENABLEMENT_SELECTOR: |-
        - podSelector:
            matchLabels:
              istio.io/dataplane-mode: ambient
        - namespaceSelector:
            matchLabels:
              istio.io/dataplane-mode: ambient
          podSelector:
            matchExpressions:
            - key: istio.io/dataplane-mode
              operator: NotIn
              values:
              - none
    AMBIENT_IPV6: "true"
    AMBIENT_RECONCILE_POD_RULES_ON_STARTUP: "false"
    CHAINED_CNI_PLUGIN: "true"
    CURRENT_AGENT_VERSION: 1.27.0
    EXCLUDE_NAMESPACES: kube-system
    ISTIO_OWNED_CNI_CONFIG: "false"
    NATIVE_NFTABLES: "false"
    REPAIR_BROKEN_POD_LABEL_KEY: cni.istio.io/uninitialized
    REPAIR_BROKEN_POD_LABEL_VALUE: "true"
    REPAIR_DELETE_PODS: "false"
    REPAIR_ENABLED: "true"
    REPAIR_INIT_CONTAINER_NAME: istio-validation
    REPAIR_LABEL_PODS: "false"
    REPAIR_REPAIR_PODS: "true"
kind: ConfigMap
metadata:
    labels:
        app: istio-cni
        app.kubernetes.io/instance: istio-cni-node-agent
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: istio-cni
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/version: 1.27.0
        helm.sh/chart: cni-1.27.0
        install.operator.istio.io/owning-resource: unknown
        istio.io/rev: default
        operator.istio.io/component: Cni
        release: istio-cni-node-agent
    name: istio-cni-config
    namespace: istio
