apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app: istiod
        app.kubernetes.io/instance: istiod
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: istiod
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/version: 1.27.0
        helm.sh/chart: istiod-1.27.0
        release: istiod
    name: istiod-gateway-controller-istio
rules:
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - create
        - delete
    - apiGroups:
        - autoscaling
      resources:
        - horizontalpodautoscalers
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - create
        - delete
    - apiGroups:
        - policy
      resources:
        - poddisruptionbudgets
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - create
        - delete
    - apiGroups:
        - ""
      resources:
        - services
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - create
        - delete
    - apiGroups:
        - ""
      resources:
        - serviceaccounts
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - create
        - delete
